---
apiVersion: v1
kind: Namespace
metadata:
  name: game-2048
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: game-2048
  name: deployment-2048
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-2048
  replicas: 2 # You can adjust the number of replicas as needed
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-2048
    spec:
      containers:
      - image:  ghcr.io/prazeina/docker-2048:sha-66ca783 # Replace with your 2048 game image
        imagePullPolicy: IfNotPresent # Or Always if you want to ensure latest image pull
        name: app-2048
        ports:
        - containerPort: 80 # The port your 2048 game container listens on
---
apiVersion: v1
kind: Service
metadata:
  namespace: game-2048
  name: service-2048
spec:
  ports:
    - port: 80 # The port the service will listen on
      targetPort: 80 # The port on the pods to forward traffic to
      protocol: TCP
  type: NodePort # Exposes the service on a port on each node
  selector:
    app.kubernetes.io/name: app-2048